name: CI on Push
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Display Push Event Details
      run: |
        echo "Push event on branch ${{ github.ref }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Pusher: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
